/** biome-ignore-all lint/a11y/noStaticElementInteractions: biome is dumb */
/** biome-ignore-all lint/a11y/useKeyWithClickEvents: biome is dumb */
interface AboutModalProps {
	isOpen: boolean
	onClose: () => void
}

export function AboutModal({ isOpen, onClose }: AboutModalProps) {
	if (!isOpen) return null

	return (
		<div className="fixed inset-0 z-2000 flex items-center justify-center bg-white/90" onClick={onClose}>
			<div
				className="relative max-h-[80vh] w-[90%] max-w-[600px] overflow-y-auto bg-white p-10 shadow-2xl"
				onClick={e => e.stopPropagation()}
			>
				<button
					type="button"
					onClick={onClose}
					className="absolute top-4 right-4 cursor-pointer text-3xl text-gray-800 leading-none hover:text-black"
					aria-label="Close"
				>
					×
				</button>

				<h2 className="mb-5 text-2xl text-gray-800">About AI World Clocks</h2>

				<p className="mb-4 text-gray-800 leading-relaxed">
					Every minute, a new clock is displayed that has been generated by nine different AI models.
				</p>

				<p className="mb-4 text-gray-800 leading-relaxed">
					Each model is allowed 2000 tokens to generate its clock. Here is its prompt:
				</p>

				<code className="my-4 block whitespace-pre-wrap break-words bg-gray-100 p-4 font-mono text-gray-600 text-sm">
					{`Create HTML/CSS of an analog clock showing \${time}. Include numbers (or numerals) if you wish, and have a CSS animated second hand. Make it responsive and use a white background. Return ONLY the HTML/CSS code with no markdown formatting.`}
				</code>

				<p className="mb-4 text-gray-800 leading-relaxed">
					Clone of{' '}
					<a href="https://clocks.brianmoore.com" className="text-gray-800 underline hover:text-black">
						AI World Clocks
					</a>{' '}
					by Brian Moore, but with the latest AI models. Built with Supabase and React.
				</p>
			</div>
		</div>
	)
}
