interface AboutModalProps {
  isOpen: boolean
  onClose: () => void
}

export function AboutModal({ isOpen, onClose }: AboutModalProps) {
  if (!isOpen) return null

  return (
    <div
      className="fixed inset-0 bg-white/90 flex items-center justify-center z-[2000]"
      onClick={onClose}
    >
      <div
        className="bg-white p-10 max-w-[600px] w-[90%] max-h-[80vh] overflow-y-auto relative shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-3xl cursor-pointer text-gray-800 leading-none hover:text-black"
          aria-label="Close"
        >
          ×
        </button>

        <h2 className="text-2xl mb-5 text-gray-800">About AI World Clocks</h2>

        <p className="mb-4 leading-relaxed text-gray-800">
          Every minute, a new clock is displayed that has been generated by nine different AI models.
        </p>

        <p className="mb-4 leading-relaxed text-gray-800">
          Each model is allowed 2000 tokens to generate its clock. Here is its prompt:
        </p>

        <code className="block bg-gray-100 text-gray-600 p-4 my-4 font-mono text-sm whitespace-pre-wrap break-words">
          {`Create HTML/CSS of an analog clock showing \${time}. Include numbers (or numerals) if you wish, and have a CSS animated second hand. Make it responsive and use a white background. Return ONLY the HTML/CSS code with no markdown formatting.`}
        </code>

        <p className="mb-4 leading-relaxed text-gray-800">
          Clone of{' '}
          <a href="https://clocks.brianmoore.com" className="text-gray-800 underline hover:text-black">
            AI World Clocks
          </a>{' '}
          by Brian Moore, but with the latest AI models. Built with Supabase and React.
        </p>
      </div>
    </div>
  )
}
